-- database/seed.sql

-- Insert Default Admin (Password: admin123)
-- Hash generated by password_hash('admin123', PASSWORD_DEFAULT)
INSERT INTO users (name, email, password, role) VALUES 
('Administrator', 'admin@library.com', '$2y$10$L1bYv/6mG1Hh3y8wZ/zJ.eVT80dI09E1mS1.v8Xy6gMv.yW/Q2r5C', 'admin');

-- Insert Default Member (Password: member123)
-- Hash generated by password_hash('member123', PASSWORD_DEFAULT)
INSERT INTO users (name, email, password, role) VALUES 
('Ahmad Member', 'member@library.com', '$2y$10$3zR1i5yMvT8.35.s3gH8G.u8O0K9gL3L7b5jG7eT8Q0vW5qX1mS1O', 'member');

-- Insert Dummy Books
INSERT INTO books (title, author, publisher, published_year, isbn, stock, description) VALUES 
('Belajar Pemrograman PHP Dasar', 'Budi Raharjo', 'Informatika', 2021, '978-602-1234-56-7', 5, 'Buku panduan lengkap belajar PHP untuk pemula, mencakup dasar-dasar sintaks, array, fungsi, dan interaksi dengan database.'),
('Mastering PostgreSQL 13', 'Hans-Jürgen Schönig', 'Packt Publishing', 2020, '978-180-056-749-8', 3, 'Panduan tingkat lanjut untuk menguasai PostgreSQL, optimasi query, dan manajemen performa.'),
('Struktur Data dan Algoritma', 'Erickson', 'Andi Publisher', 2019, '978-979-29-1234-5', 2, 'Mempelajari konsep struktur data (Linked List, Tree, Graph) dan algoritma pengurutan (Sorting) serta pencarian (Searching).'),
('Desain Web dengan Tailwind CSS', 'Adam Wathan', 'Independen', 2022, '978-0-123456-78-9', 4, 'Buku praktis mempelajari framework utility-first Tailwind CSS untuk membuat antarmuka web yang modern dan responsif.'),
('Dasar-dasar Jaringan Komputer', 'Tanenbaum', 'Prentice Hall', 2018, '978-0-13-212695-3', 1, 'Buku referensi utama untuk memahami konsep jaringan komputer, protokol TCP/IP, dan model OSI.');
